// Copyright (C) 2014 Nippon Telegraph and Telephone Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package rtmon

type RTMSGTYPE int

const (
	RTM_BASE         RTMSGTYPE = 0x10
	RTM_DELACTION    RTMSGTYPE = 0x31
	RTM_DELADDR      RTMSGTYPE = 0x15
	RTM_DELADDRLABEL RTMSGTYPE = 0x49
	RTM_DELLINK      RTMSGTYPE = 0x11
	RTM_DELNEIGH     RTMSGTYPE = 0x1d
	RTM_DELQDISC     RTMSGTYPE = 0x25
	RTM_DELROUTE     RTMSGTYPE = 0x19
	RTM_DELRULE      RTMSGTYPE = 0x21
	RTM_DELTCLASS    RTMSGTYPE = 0x29
	RTM_DELTFILTER   RTMSGTYPE = 0x2d
	RTM_F_CLONED     RTMSGTYPE = 0x200
	RTM_F_EQUALIZE   RTMSGTYPE = 0x400
	RTM_F_NOTIFY     RTMSGTYPE = 0x100
	RTM_F_PREFIX     RTMSGTYPE = 0x800
	RTM_GETACTION    RTMSGTYPE = 0x32
	RTM_GETADDR      RTMSGTYPE = 0x16
	RTM_GETADDRLABEL RTMSGTYPE = 0x4a
	RTM_GETANYCAST   RTMSGTYPE = 0x3e
	RTM_GETDCB       RTMSGTYPE = 0x4e
	RTM_GETLINK      RTMSGTYPE = 0x12
	RTM_GETMULTICAST RTMSGTYPE = 0x3a
	RTM_GETNEIGH     RTMSGTYPE = 0x1e
	RTM_GETNEIGHTBL  RTMSGTYPE = 0x42
	RTM_GETQDISC     RTMSGTYPE = 0x26
	RTM_GETROUTE     RTMSGTYPE = 0x1a
	RTM_GETRULE      RTMSGTYPE = 0x22
	RTM_GETTCLASS    RTMSGTYPE = 0x2a
	RTM_GETTFILTER   RTMSGTYPE = 0x2e
	RTM_MAX          RTMSGTYPE = 0x4f
	RTM_NEWACTION    RTMSGTYPE = 0x30
	RTM_NEWADDR      RTMSGTYPE = 0x14
	RTM_NEWADDRLABEL RTMSGTYPE = 0x48
	RTM_NEWLINK      RTMSGTYPE = 0x10
	RTM_NEWNDUSEROPT RTMSGTYPE = 0x44
	RTM_NEWNEIGH     RTMSGTYPE = 0x1c
	RTM_NEWNEIGHTBL  RTMSGTYPE = 0x40
	RTM_NEWPREFIX    RTMSGTYPE = 0x34
	RTM_NEWQDISC     RTMSGTYPE = 0x24
	RTM_NEWROUTE     RTMSGTYPE = 0x18
	RTM_NEWRULE      RTMSGTYPE = 0x20
	RTM_NEWTCLASS    RTMSGTYPE = 0x28
	RTM_NEWTFILTER   RTMSGTYPE = 0x2c
	RTM_NR_FAMILIES  RTMSGTYPE = 0x10
	RTM_NR_MSGTYPES  RTMSGTYPE = 0x40
	RTM_SETDCB       RTMSGTYPE = 0x4f
	RTM_SETLINK      RTMSGTYPE = 0x13
	RTM_SETNEIGHTBL  RTMSGTYPE = 0x43
)

type RTATTRTYPE int

const (
	RTA_UNSPEC    RTATTRTYPE = 0x0
	RTA_DST       RTATTRTYPE = 0x1
	RTA_SRC       RTATTRTYPE = 0x2
	RTA_IIF       RTATTRTYPE = 0x3
	RTA_OIF       RTATTRTYPE = 0x4
	RTA_GATEWAY   RTATTRTYPE = 0x5
	RTA_PRIORITY  RTATTRTYPE = 0x6
	RTA_PREFSRC   RTATTRTYPE = 0x7
	RTA_METRICS   RTATTRTYPE = 0x8
	RTA_MULTIPATH RTATTRTYPE = 0x9
	RTA_FLOW      RTATTRTYPE = 0xb
	RTA_CACHEINFO RTATTRTYPE = 0xc
	RTA_TABLE     RTATTRTYPE = 0xf
)
