// generated by stringer -type RTATTRTYPE const.go; DO NOT EDIT

package rtmon

import "fmt"

const (
	_RTATTRTYPE_name_0 = "RTA_UNSPECRTA_DSTRTA_SRCRTA_IIFRTA_OIFRTA_GATEWAYRTA_PRIORITYRTA_PREFSRCRTA_METRICSRTA_MULTIPATH"
	_RTATTRTYPE_name_1 = "RTA_FLOWRTA_CACHEINFO"
	_RTATTRTYPE_name_2 = "RTA_TABLE"
)

var (
	_RTATTRTYPE_index_0 = [...]uint8{0, 10, 17, 24, 31, 38, 49, 61, 72, 83, 96}
	_RTATTRTYPE_index_1 = [...]uint8{0, 8, 21}
	_RTATTRTYPE_index_2 = [...]uint8{0, 9}
)

func (i RTATTRTYPE) String() string {
	switch {
	case 0 <= i && i <= 9:
		return _RTATTRTYPE_name_0[_RTATTRTYPE_index_0[i]:_RTATTRTYPE_index_0[i+1]]
	case 11 <= i && i <= 12:
		i -= 11
		return _RTATTRTYPE_name_1[_RTATTRTYPE_index_1[i]:_RTATTRTYPE_index_1[i+1]]
	case i == 15:
		return _RTATTRTYPE_name_2
	default:
		return fmt.Sprintf("RTATTRTYPE(%d)", i)
	}
}
